[tool.poetry]
name = "tomegathericon-utils-exceptions"
version = "0.0.1"
description = "Various High Level Exceptions"
license = "Software License Agreement"
authors = ["Abhishek Kapoor <kapoor.abhishek@outlook.com>"]
packages = [{include = "tomegathericon/utils/exceptions"}]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
sphinx = "^8.2.3"
twine = "^6.1.0"
pylint = "^3.3.7"
isort = "^6.0.1"
mypy = "^1.17.1"
