[project]
name = "owlidar"
version = "0.1.10"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bayan2019", email = "saparbayevabt@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.1",
    "requests>=2.32.4",
]

[project.scripts]
owlidar = "owlidar:main"

[build-system]
requires = ["uv_build>=0.8.2,<0.9.0"]
build-backend = "uv_build"
