[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "BoatBuddy"
version = "0.16.0"
authors = [
    { name = "Joe Zeitouny", email = "joezeitouny@gmail.com" },
]
description = "A suite of tools to help collecting NMEA0183 and other marine metrics in a digital logbook format"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pyobjc ~= 9.0.1;sys_platform == 'darwin'",
    "geopy ~= 2.3.0",
    "gpxpy ~= 1.5.0",
    "latloncalc ~= 1.5.3",
    "openpyxl ~= 3.0.10",
    "pyModbusTCP ~= 0.2.0",
    "Events ~= 0.4",
    "numpy ~= 1.24.1",
    "rich ~= 13.3.1",
    "pyserial",
    "keyring ~= 23.13.1",
    "Flask ~= 3.0.2",
    "python-telegram-bot ~= 20.6",
    "bleak~=0.21.1",
    "victron-ble~=0.6.0",
    "pydub",
    "requests"
]
[project.urls]
"Homepage" = "https://boatbuddy.site"
"Bug Tracker" = "https://github.com/joezeitouny/BoatBuddy/issues"