[project]
name = "dagster-slurm"
version = "1.1.0-rc.4"
description = "dagster integration with slurm"
readme = "README.md"
authors = [{ name = "geoheil", email = "georg.heiler@ascii.ac.at" }]
requires-python = ">=3.12"
license = { text = "Apache-2.0" }
keywords = ["dagster", "slurm", "hpc", "workflow-orchestration", "ray", "feray"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers", 
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Topic :: System :: Distributed Computing",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = []

[project.urls]
Homepage = "https://ascii-supply-networks.github.io/dagster-slurm/"
Repository = "https://github.com/ascii-supply-networks/dagster-slurm"
Documentation = "https://ascii-supply-networks.github.io/dagster-slurm/docs/intro"
"Bug Reports" = "https://github.com/ascii-supply-networks/dagster-slurm/issues"

[tool.uv.sources]
feray = { workspace = true }

[tool.uv.build-backend]
module-root = ""

[build-system]
requires = ["uv_build>=0.8.6,<0.9"]
build-backend = "uv_build"
