[build-system]
requires = ['setuptools>=42']
build-backend = 'setuptools.build_meta'

[project]
name = "zwergetl-components-base"
version = "0.2.3"
maintainers = [{name = "dxdataworks"}]
description = "Basic components for ZwergETL Engine"
readme = "README.md"
requires-python = ">=3.6"
dependencies = [
    "zwergetl-engine >=0.1.11"
]
