[project]
name = "test_genie" 
version = "0.1.9"
description = "CLI tool to auto-generate test cases from your code"
authors = [{ name = "Kushagra Wadhwa", email = "testgenieofficial@gmail.com" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.7"
dependencies = ["click==8.1.7",
"requests==2.31.0",
"pathlib2==2.3.7" ]

[project.scripts]
test-genie = "cli.main:cli"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"