[build-system]
requires = ["setuptools>=62.4.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tree-sitter-orca"
description = "Parser for input file for the Orca quantum chemistry package"
version = "0.1.0"
keywords = ["incremental", "parsing", "tree-sitter", "orca"]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]
authors = [{ name = "Kalman Szenes", email = "szenes.kalman@gmail.com" }]
requires-python = ">=3.10"
license.text = "MIT"
readme = "README.md"
dependencies = [
    "build>=1.3.0",
    "twine>=6.1.0",
]

[project.urls]
Homepage = "https://github.com/tree-sitter/tree-sitter-orca"

[project.optional-dependencies]
core = ["tree-sitter~=0.24"]

[tool.cibuildwheel]
build = "cp310-*"
build-frontend = "build"
