[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "glycotrans"
version = "0.1.1"
authors = [
    {name = "Rudiyanto Gunawan", email = "rgunawan@buffalo.edu"},
    {name = "Ejas Abtheen", email = "ejasalth@buffalo.edu"},
    ]
description = """A python package for glycan structure prediction from mass spectrometry data 
                 using transformer based models -- GlycoBERT and GlycoBART."""
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.9"
dependencies =[
        "CandyCrunch==0.6.0",
        "glycowork~=1.6.1",
        "torch>2.1",
        "transformers>=4.50.0,<5.0.0",
        "pandas",
        "numpy",
        "pyopenms~=3.4"
    ]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/CABSEL/glycotrans.git"

[tool.setuptools]
include-package-data = true
packages = ["glycotrans"]

[tool.setuptools.package-data]
"*" = ["*.csv", "*.pkl", "*.json", "*.pt", "*.txt"]
