[tool.poetry]
name = "lsrestclient"
version = "3.3.1"
description = "REST Api Client"
authors = ["mba <bartel@electronic-shop.lu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.31.0"
lsjsonclasses = "^2.0.1"
pydash = ">4.0.0"
webexception = "^1.0.5"
requests-cache = "^1.2.1"
pydantic = "^2.11.7"
pydantic-settings = "^2.10.1"
redis = "^6.4.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.7.0"
fastapi = "^0.104.1"
uvicorn = "^0.35.0"
killport = "^1.2.0"
fastapi-lsoft = "^1.0.0"

[tool.poetry.extras]
redis = ["redis"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -s -v"
testpaths = [
    "tests",
]
log_cli = true
log_cli_level = "DEBUG"
#log_cli_level = "INFO"
#log_cli_format = "[%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_format = "[%(name)s][%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"

[tool.black]
line-length = 120

[tool.poetry.plugins.pytest11]
"lsrestclient" = "lsrestclient.fixtures"
