[project]
name = "spacelink"
version = "0.1.5"
authors = [
  { name = "Jacob Portukalian", email = "jacob@cascade.space" },
  { name = "Arlen Abraham", email = "arlen@cascade.space" },
  { name = "Brett Gottula", email = "brett@cascade.space" },
]
description = "Space link budget calculation package"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "numpy>=2.0.0,<3.0.0",
    "scipy>=1.10.0,<2.0.0",
    "astropy>=7.0.1,<8.0.0",
    "pydantic (>=2.11.7,<3.0.0)",
]

[project.urls]
homepage = "https://github.com/cascade-space-co/spacelink"
issues = "https://github.com/cascade-space-co/spacelink/issues"
documentation = "https://cascade-space-co.github.io/spacelink"

[tool.poetry]
packages = [{include = "spacelink", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
pyyaml = "^6.0.2"
black = {extras = ["jupyter"], version = "^25.1.0"}
flake8 = "^7.0.0"
sphinx = "^7.2.6"
sphinx-rtd-theme = "^2.0.0"
renku-sphinx-theme = "^0.5.0"
sphinx-autodoc-typehints = "^1.25.2"
wheel = "^0.45.1"
twine = "^6.1.0"

[tool.poetry.group.demo.dependencies]
jupyter = "^1.0.0"
notebook = "^7.0.6"
matplotlib = "^3.8.2"
ipykernel = "^6.27.1"
ipympl = "^0.9.7"
ipywidgets = "^8.1.7"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
max-line-length = 100
exclude = [".git", "__pycache__", "build", "dist"]

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = [
    "tests"
]
python_files = ["test_*.py"]
python_functions = ["test_*"]

[tool.coverage.run]
source = ["src"]
branch = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:",
    "raise NotImplementedError",
]
show_missing = true
fail_under = 90
