[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bdtariff"
version = "1.0.2"
dependencies = [
        "requests",
    ]
authors = [
  { name="Md.Shamim-Ul-Islam", email="nbrshamim@gmail.com" },
]
description = "Tariff rate and duty calculation based on Bangladesh Import and Export related H.S. Code"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/nbrshamim/bdtariff"
Issues = "https://github.com/nbrshamim/bdtariff"