[tool.poetry]
name = "lunary"
version = "1.4.26-alpha.5"
description = "Python SDK for Lunary, the open-source platform where GenAI teams manage and improve LLM chatbots."
authors = ["lunary <hello@lunary.ai>"]
readme = "README.md"
repository = "https://github.com/lunary-ai/lunary/tree/main/packages/python-sdk"
documentation = "https://lunary.ai/docs/py"
homepage = "https://lunary.ai/docs/py"
keywords = [
  "Lunary",
  "lunary.ai",
  "Langchain",
  "AI",
  "Analytics",
  "Monitoring",
  "LLM",
  "GenAI",
  "SDK",
]

[tool.poetry.dependencies]
python = ">=3.10.0,<=3.15"
requests = "^2.32.4"
setuptools = ">=78.1.1"
tenacity = "^8.5.0"
packaging = "^23.2"
chevron = "^0.14.0"
pyhumps = "^3.8.0"
aiohttp = "^3.12.15"
pydantic = "^2.11.7"
jsonpickle = "^4.1.1"

[tool.poetry.group.dev.dependencies]
openai = "^1.99.6"
pytest = "^8.4.1"
ibm-watsonx-ai = { version = "^1.3.32", python = "<3.14" }
langchain-core = "^0.3.74"
langchain-community = "^0.3.27"
langchain-openai = "^0.3.29"
langgraph = "^0.6.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
