[project]
name = "pyspark-toolkit"
dynamic = ["version"]
description = "PySpark Utils"
readme = "README.md"
requires-python = ">=3.9.0"



[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "psutil>=7.0.0",
    "pytest>=8.4.1",
    "ruff>=0.12.7",
    "pyspark>=3.5.0",
]

[project.optional-dependencies]
pyspark = [
    "pyspark>=3.5.0",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["I"]

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["pyspark_toolkit*"]
exclude = ["pyspark_toolkit.s3"]

[tool.setuptools.dynamic]
version = { attr = "pyspark_toolkit.__version__" }


[[tool.uv.index]]
name = "pyspark"
url = "https://pypi.org/simple"
default = true
