[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "PyMailkit"
version = "2.0.0"
description = "A modern Python library for sending and receiving emails with SMTP and IMAP support"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
keywords = ["email", "smtp", "imap", "mail", "email-client","pymail"]
authors = [
  {name = "Kailas P S", email = "kailaspsudheer@gmail.com"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Communications :: Email",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/kailasps/pymailkit"
Repository = "https://github.com/kailasps/pymailkit.git"
"Bug Tracker" = "https://github.com/kailasps/pymailkit/issues"
License = "https://github.com/kailasps/pymailkit/blob/main/LICENSE"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["pymailkit"]