[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "maleo-cds"  # PyPI package name
version = "0.1.3"
description = "MaleoCDS service package"
authors = [
    { name = "Agra Bima Yuda", email = "agra@nexmedis.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "maleo_soma>=0.1.45",
    "maleo_metadata>=0.2.5"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["maleo_cds*"]

[tool.setuptools.package-data]
maleo_cds = ["*.json", "*.yaml"]

[project.scripts]
# Uncomment and modify if you have CLI tools
# maleo-cli = "maleo_cds.cli:main"