# pyproject.toml 

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-web-extractor-sadasiba"
version = "0.1.3"
description = "MCP server that extracts content from web pages for LLMs"
readme = "README.md"
authors = [
    {name = "sadasiba", email = "sadasiba@gmail.com"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "mcp>=1.2.0",
    "requests",
    "beautifulsoup4",
]
requires-python = ">=3.9"

[project.scripts]
mcp-web-extractor-sadasiba = "web_extractor.server:mcp.run"

[tool.setuptools]
package-dir = {"" = "src"}