[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "thermo_stability"
version = "0.0.5"
authors = [
  { name="Sara Nabili", email="srnabili@gmail.com" },
]
description = "Thermodynamic stability of chemical compound using DNN."
readme = "README.md"
requires-python = ">=3.10.17"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "matplotlib==3.8.2",
    "numpy==1.26.4",
    "pandas",
    "scikit-learn==1.3.2",
    "tensorflow-macos==2.15.0",
    "tensorflow-metal==1.1.0",
    "xgboost==2.0.3",
    "scikeras==0.12.0",
    "joblib",
    "argparse",
    "psutil",
    "tqdm",
    "mp-api==0.45.5",
    "pymatgen",
]
