[build-system]
requires = ["setuptools==75.8.0"]  # metadata-version = "2.2"
build-backend = "setuptools.build_meta"

[project]
name = "gahto"
version = "0.0.1"
authors = [
	{name = "7heo", email = "7heo@users.noreply.github.com"}
]
readme = "README.md"
description = "GAHTO is a small Python module for creating GNUCash Account Hierarchy Template Objects natively in python, and eventually exporting them in XML as .gnucash-xea files."
requires-python = ">=3.9"
dependencies = [
	"pint",
	"iso-4217"
]
classifiers = [
	"Programming Language :: Python :: 3",
	"Operating System :: OS Independent",
]
license = {"text" = "BSD-3-Clause"}

[project.urls]
Homepage = "https://github.com/7heo/GAHTO"
Issues = "https://github.com/7heo/GAHTO/issues"

[tool.setuptools.package-data]
pkg = ["py.typed"]
