[project]
name = "djson-form"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django==5.2",
]

[tool.setuptools]
packages = ["djson_form"]
