[build-system]
requires = ["flit_scm",]
build-backend = "flit_scm:buildapi"

[project]
name = "memberjojo"
authors = [{name = "Duncan Bellamy", email = "dunk@denkimushi.com"}]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/a16bitsysop/memberjojo"

[project.optional-dependencies]
dev = [
    "flit",
    "pytest",
]
lint = [
    "black",
    "coverage",
    "pylint",
]
docs = [
    "furo",                       # HTML theme
    "myst-parser>=2.0",           # For Markdown support
    "sphinx>=7.0",
    "sphinx-autodoc-typehints",   # For cleaner type hints in docs
]

[tool.flit.sdist]
exclude = [".gitignore"]

[tool.setuptools_scm]
write_to = "src/memberjojo/_version.py"

[tool.pytest.ini_options]
pythonpath = [ "src" ]

[tool.pylint.main]
output-format = "colorized"
verbose = true
ignore = ["docs"]
ignore-patterns = ["_version.py"]
