[project]
name = "jentic"
version = "0.9.1"
description = "Jentic SDK for the discovery and execution of APIs and workflows"
requires-python = ">=3.11"
readme = "README.md"
authors = [
    { name = "Jentic Labs", email = "info@jenticlabs.com" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "arazzo-runner>=0.8.19",
    "pydantic>=2.0.0",
    "httpx>=0.28.1",
    "tenacity>=9.1.2",
]

[project.license]
text = "MIT"

[dependency-groups]
dev = [
    "pytest>=7.4.0",
    "mypy>=1.5.1",
    "black>=23.7.0",
    "ruff>=0.0.289",
    "pytest-asyncio>=0.25.3",
    "pytest-coverage>=0.0",
    "sphinx>=8.2.3",
    "sphinx-autodoc-typehints>=3.2.0",
    "sphinxcontrib-mermaid>=1.0.0",
    "sphinx-copybutton>=0.5.2",
    "sphinxcontrib-napoleon>=0.7",
    "sphinx-book-theme>=1.1.4",
    "autodoc-pydantic>=2.2.0",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.black]
line-length = 100
