[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "paytechuz"
version = "0.2.21"
description = "Unified Python package for Uzbekistan payment gateways"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages]
find = {where = ["src"], include = ["paytechuz*"]}
