[tool.poetry]
name = "data_exchange_tool"
readme = "README.md"
version = "0.1.0"
authors = ["Toni Caparrós García <tonicapagarcia@gmail.com>"]
description = "Tool for django models import"

[tool.poetry.dependencies]
python = "^3.11"
celery = "^5.5.3"
redis = "^6.3.0"
boto3 = "^1.40.2"
python-decouple = "^3.8"
django = ">=3.0"
polars = "^1.32.0"
djangorestframework = "^3.16.0"
django-storages = "^1.14.6"
django-celery-results = "^2.6.0"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
build = "^1.3.0"
twine = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
