[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = [
  {name = "Xiangjian Jiang", email = "silencejiang12138@gmail.com"},
]
classifiers = [
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
]
description = "TabCamel: A DataFrame-focused solution for tabular datasets in machine learning workflows"
keywords = ["tabular data", "dataframe", "machine learning"]
license = {file = "LICENSE"}
name = "tabcamel"
readme = "README.md"
requires-python = ">=3.10"
version = "2025.08.10"

dependencies = [
  "pytest",
  "flake8",
  "pylint",
  "setuptools==75.1.0",
  "sphinx",
  "myst-parser",
  "sphinx-rtd-theme",
  "sphinx-book-theme",
  "ipykernel",
  "cloudpickle",
  "bnlearn",
  "ucimlrepo",
  "pgmpy==1.0.0",
]

[project.optional-dependencies]
dev = []
