[build-system]
requires = ["hatchling>=1.5.0", "jupyterlab>=4.0.0,<5", "hatch-nodejs-version>=0.3.2"]
build-backend = "hatchling.build"

[project]
name = "jupyterlab_logtalk_codemirror_extension"
version = "1.3.0"
description = "A JupyterLab extension for Logtalk syntax highlighting."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
authors = [
    { name = "Paulo Moura", email = "pmoura@logtalk.org" }
]
maintainers = [
    { name = "Paulo Moura", email = "pmoura@logtalk.org" }
]
keywords = [
    "jupyter",
    "jupyterlab",
    "jupyterlab-extension",
    "logtalk",
    "syntax-highlighting",
    "codemirror"
]
classifiers = [
    "Framework :: Jupyter",
    "Framework :: Jupyter :: JupyterLab",
    "Framework :: Jupyter :: JupyterLab :: 4",
    "Framework :: Jupyter :: JupyterLab :: Extensions",
    "Framework :: Jupyter :: JupyterLab :: Extensions :: Prebuilt",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "jupyterlab>=4.0.0,<5",
]

[project.urls]
Homepage = "https://github.com/LogtalkDotOrg/jupyterlab-logtalk-codemirror-extension"
Repository = "https://github.com/LogtalkDotOrg/jupyterlab-logtalk-codemirror-extension.git"
"Bug Tracker" = "https://github.com/LogtalkDotOrg/jupyterlab-logtalk-codemirror-extension/issues"

[tool.hatch.build.targets.sdist]
artifacts = ["jupyterlab_logtalk_codemirror_extension/labextension"]
exclude = [".github", "binder"]

[tool.hatch.build.targets.wheel.shared-data]
"jupyterlab_logtalk_codemirror_extension/labextension" = "share/jupyter/labextensions/jupyterlab_logtalk_codemirror_extension"
"install.json" = "share/jupyter/labextensions/jupyterlab_logtalk_codemirror_extension/install.json"

[tool.hatch.build.hooks.jupyter-builder]
dependencies = ["hatch-jupyter-builder>=0.5"]
build-function = "hatch_jupyter_builder.npm_builder"
ensured-targets = [
    "jupyterlab_logtalk_codemirror_extension/labextension/static/style.js",
    "jupyterlab_logtalk_codemirror_extension/labextension/package.json",
]
skip-if-exists = ["jupyterlab_logtalk_codemirror_extension/labextension/static/style.js"]

[tool.hatch.build.hooks.jupyter-builder.build-kwargs]
build_cmd = "build:prod"
npm = ["jlpm"]

[tool.hatch.build.hooks.jupyter-builder.editable-build-kwargs]
build_cmd = "install:extension"
npm = ["jlpm"]
source_dir = "src"
build_dir = "jupyterlab_logtalk_codemirror_extension/labextension"

[tool.check-manifest]
ignore = ["jupyterlab_logtalk_codemirror_extension/labextension/**", "yarn.lock", ".*", "package-lock.json"]
