[project]
name = "langchain-anchorbrowser"
version = "0.1.3"
description = "Anchor Browser tools for LangChain"
authors = [
    {name = "Gil Dankner",email = "gil@anchorbrowser.io"}
]
readme = "README.md"
requires-python = ">=3.8,<4.0"

[tool.poetry]
packages = [{include = "langchain_anchorbrowser", from = "src" }]

[tool.poetry.dependencies]
anchorbrowser = "^0.1"
langchain-core = "^0.3.15"
pydantic = "^2.11.1"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
langchain-tests = "^0.3.20"

[tool.pytest.ini_options]
pythonpath = ["src"]

license = "MIT"
license-files = ["LICENSE"]

[build-system]
requires = [
    "poetry-core>=2.0.0,<3.0.0"
]
build-backend = "poetry.core.masonry.api"

[project.urls]
Homepage = "https://github.com/anchorbrowser/langchain-anchorbrowser"
Repository = "https://github.com/anchorbrowser/langchain-anchorbrowser"
AnchorBrowser = "https://anchorbrowser.io"