[project]
name = "koi-mcp"
version = "0.1.3"
description = "KOI Security MCP Server"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.10.0",
    "httpx>=0.27"
]
readme = "README.md"

[project.scripts]
koi-mcp = "koi_mcp.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["koi_mcp"]

[tool.hatch.build.targets.wheel]
packages = ["koi_mcp"]
include = [
    "koi_mcp/openapi.json"
]