[project]
name = "GreenWorks"
version = "0.0.2.2"
authors = [
  { name="Christian Boes", email="boes9@icloud.com" },
]
description = "An API wrapper for the Greenworks robotic lawn mower"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

license = "MIT"

[project.urls]
Documentation = "https://github.com/Boes24/GreenWorks-Core"
Issues = "https://github.com/Boes24/GreenWorks-Core/issues"