[project]
name = "ctrlstack"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.11.5",
    "pandas>=2.3.0",
    "python-dotenv>=1.1.0",
    "rich>=14.0.0",
    "fastapi[standard]>=0.116.1",
    "typer>=0.16.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
ignore-vcs = true
packages = ["ctrlstack"]
include = [
]

[dependency-groups]
dev = [
    "jupyterlab>=4.4.0",
    "nblite>=0.6.0,<0.7.0",
    "twine>=6.1.0",
]

[project.scripts]
ctrlstack = "ctrlstack.cli.app:app"
