[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "demo_ezto"
version = "0.1.0"
description = "A CLI tool to set up a FastAPI Python project structure with sample code"
authors = [{ name = "Varsha", email = "varsha.s@grootan.com" }]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",  # Change if needed
]

[project.scripts]
demo_ezto = "demo_ezto.main:main"