[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=77.0.3"]

[project]
name = "types-JACK-Client"
version = "0.5.10.20250809"
license = "Apache-2.0"
license-files = ["LICENSE"]
description = "Typing stubs for JACK-Client"
readme = { text = """\
## Typing stubs for JACK-Client

This is a [PEP 561](https://peps.python.org/pep-0561/) type stub package for
the [`JACK-Client`](https://github.com/spatialaudio/jackclient-python) package. It can be used by type checkers
to check code that uses `JACK-Client`. This version of
`types-JACK-Client` aims to provide accurate annotations for
`JACK-Client==0.5.*`.

This package is part of the [typeshed project](https://github.com/python/typeshed).
All fixes for types and metadata should be contributed there.
See [the README](https://github.com/python/typeshed/blob/main/README.md)
for more details. The source for this package can be found in the
[`stubs/JACK-Client`](https://github.com/python/typeshed/tree/main/stubs/JACK-Client)
directory.

This package was tested with the following type checkers:
* [mypy](https://github.com/python/mypy/) 1.16.1
* [pyright](https://github.com/microsoft/pyright) 1.1.403

It was generated from typeshed commit
[`91ba0da4aad754c912a82b9e052cb4f8191ce520`](https://github.com/python/typeshed/commit/91ba0da4aad754c912a82b9e052cb4f8191ce520).
""", content-type = "text/markdown" }
classifiers = [
  "Programming Language :: Python :: 3",
  "Typing :: Stubs Only",
]
requires-python = ">=3.9"
dependencies = ['types-cffi', 'numpy>=1.20']

[project.urls]
"Homepage" = "https://github.com/python/typeshed"
"GitHub" = "https://github.com/python/typeshed"
"Changes" = "https://github.com/typeshed-internal/stub_uploader/blob/main/data/changelogs/JACK-Client.md"
"Issue tracker" = "https://github.com/python/typeshed/issues"
"Chat" = "https://gitter.im/python/typing"

[tool.setuptools]
packages = ['jack-stubs']
include-package-data = false
