[project]
name = "odooss"
version = "0.1.0"
description = "IdeaCode Academy Odoo Standard Structure â€” starting point repo."
requires-python = ">=3.10"
dependencies = [
    "ruff>=0.12.8",
    "black>=24.0.0",
    "isort>=5.13.0",
    "pre-commit>=3.8.0",
    "click>=8.2.1",
]

authors = [
    { name = "Agga", email = "hanzawnyineonline@gmail.com" }
]

[project.urls]
Homepage = "https://github.com/HanZawNyein/ica_standard_structure.git"
Repository = "https://github.com/HanZawNyein/ica_standard_structure.git"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors (PEP 8)
    "F",  # pyflakes errors
    "W",  # pycodestyle warnings
    "B",  # flake8-bugbear (extra best practices)
    "I",  # isort import checks
]
ignore = [
    "E501",  # Optional: ignore line-length if Black handles it
]

[tool.black]
line-length = 88
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 88

[tool.uv.sources]
iss = { workspace = true }


[project.scripts]
iss = "iss.cli:cli"