[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "syndatagenyolo"
version = "0.1.10"
description = "A package for generating synthetic data, using labelme and generating synthetic images."
readme = "README.md"
authors = [{ name = "Sebastian JÃ¶rz", email = "seppel8426@gmail.com" }]
license = { file = "LICENSE" }
dependencies = [
    "albumentations>=2.0.8",
    "joblib>=1.5.1",
    "kaggle>=1.7.4.5",
    "labelme>=5.8.3",
    "scikit-image>=0.25.2",
    "shapely>=2.1.1",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
    "ultralytics>=8.3.175",
]


[tool.uv.workspace]
members = [
    "demo",
]

[tool.setuptools]
packages = ["syndatagenyolo"]

[project.scripts]
syndatagenyolo = "syndatagenyolo.cli.main:main"
syn_data_gen-extract = "syndatagenyolo.cli.extract_cli:main"

