[project]
name = "vipaxel"
version = "0.2.1"
description = "Collection of Dataframe helpers to plot and store data"
authors = [
    {name = "Joe Shmo",email = "joe.burge.iii@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "polars (>=1.29.0,<2.0.0)",
    "plotly (>=6.0.1,<7.0.0)",
    "pint (>=0.24.4,<0.25.0)",
    "pyyaml (>=6.0.2,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
tardb_create = "vipaxel.run_tardb:tardb_create"
tardb_print_entries = "vipaxel.run_tardb:tardb_print_entries"
tardb_add_entries = "vipaxel.run_tardb:tardb_add_entries"
tardb_delete_entries = "vipaxel.run_tardb:tardb_delete_entries"
tardb_print_entry = "vipaxel.run_tardb:tardb_print_entry"
