[project]
name = "dpg_styleqs"
version = "0.1.1"
authors = [
  { name="qsouhe", email="qsouhe@gmail.com" },
]
description = "Module created for DearpyGui, contains layout for widgets, new themes and new features"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dearpygui>=2.1.0",
    "numpy>=2.3.2",
    "pillow>=11.3.0"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/Qsouhe/dpg_styleqs"