[project]
name = "yta-video-opencv"
version = "0.0.6"
description = "Youtube Autonomous Video OpenCV Module"
authors = [
    {name = "danialcala94",email = "danielalcalavalera@gmail.com"}
]
readme = "README.md"
requires-python = "==3.9"
dependencies = [
    "yta_validation (>=0.0.1,<1.0.0)",
    "yta_constants (>=0.0.1,<1.0.0)",
    "yta_colors (>=0.0.1,<1.0.0)",
    "yta_video_frame_time (>=0.0.1,<1.0.0)",
    # This 'yta_timer' is just for manual testing
    "yta_timer (>=0.0.1,<1.0.0)",
    # This 'yta_general_utils' is just for manual
    # testing, at least by now
    "yta_general_utils (>=0.0.1,<1.0.0)",
    # This 'yta_random' is for manual testing
    "yta_random (>=0.0.1,<1.0.0)",
    "opencv-python (>=0.0.1,<9.0.0)",
    "numpy (>=0.0.1,<9.0.0)",
    # "scipy (>=0.0.1,<9.0.0)",
    # "imutils (>=0.0.1,<9.0.0)",
]

[tool.poetry]
packages = [{include = "yta_video_opencv", from = "src"}]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
