[project]
name = "avi_tools"
version = "1.0.0"
description = "Avi's Python toolkit including async function manager, variable database, and terminal utilities."
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "Avi Twil", email = "avitwil@gmail.com" }
]
dependencies = []

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://pypi.org/project/avi_tools/"
Repository = "https://github.com/avitwil/avi_tools"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["avi_tools*"]
