[package]
name = "chik"
version = "0.27.0"
edition = "2021"
license = "Apache-2.0"
description = "A meta-crate that exports all of the Chik crates in the workspace."
authors = [
    "Richard Kiss <him@richardkiss.com>",
    "Arvid Norberg <arvid@chiknetwork.com>",
    "Brandon Haggstrom <b.haggstrom@chiknetwork.com>"
]
homepage = "https://github.com/Chik-Network/chik_rs"
repository = "https://github.com/Chik-Network/chik_rs"

[workspace]
members = ["crates/*", "wheel"]

[workspace.lints.rust]
rust_2018_idioms = { level = "deny", priority = -1 }
rust_2021_compatibility = { level = "deny", priority = -1 }
future_incompatible = { level = "deny", priority = -1 }
nonstandard_style = { level = "deny", priority = -1 }
unsafe_code = "deny"
non_ascii_idents = "deny"
unused_imports = "warn"
unused_import_braces = "deny"
unreachable_code = "deny"
unreachable_patterns = "deny"
dead_code = "deny"
deprecated = "deny"
deprecated_in_future = "deny"
trivial_casts = "deny"
trivial_numeric_casts = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
must_use_candidate = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
wildcard_imports = "allow"
too_many_lines = "allow"
module_name_repetitions = "allow"
doc_markdown = "allow"
cast_possible_truncation = "allow"
cast_sign_loss = "allow"
cast_precision_loss = "allow"
cast_possible_wrap = "allow"
cast_lossless = "allow"
similar_names = "allow"
implicit_hasher = "allow"

[dependencies]
chik-bls = { workspace = true, optional = true }
chik-secp = { workspace = true, optional = true }
chik-client = { workspace = true, optional = true }
chik-consensus = { workspace = true, optional = true }
chik-protocol = { workspace = true, optional = true }
chik-ssl = { workspace = true, optional = true }
chik-serde = { workspace = true, optional = true }
chik-traits = { workspace = true, optional = true }
chik-puzzle-types = { workspace = true, optional = true }
chik-sha2 = { workspace = true, optional = true }
klvm-traits = { workspace = true, optional = true }
klvm-utils = { workspace = true, optional = true }
klvmr = { workspace = true }

# This is required since klvmr is only added here to provide the openssl feature conditionally.
# In the future we could pass the openssl feature to each of the relevant workspace crates instead.
[package.metadata.cargo-machete]
ignored = ["klvmr"]

[features]
default = [
    "bls",
    "secp",
    "client",
    "consensus",
    "protocol",
    "ssl",
    "serde",
    "traits",
    "puzzle-types",
    "sha2",
    "klvm-traits",
    "klvm-utils"
]

bls = ["dep:chik-bls", "klvm-traits/chik-bls"]
secp = ["dep:chik-secp", "klvm-traits/chik-secp"]
client = ["dep:chik-client"]
consensus = ["dep:chik-consensus"]
protocol = ["dep:chik-protocol"]
ssl = ["dep:chik-ssl"]
serde = ["dep:chik-serde", "chik-protocol/serde", "chik-bls/serde"]
traits = ["dep:chik-traits"]
puzzle-types = ["dep:chik-puzzle-types"]
sha2 = ["dep:chik-sha2"]
klvm-traits = ["dep:klvm-traits"]
klvm-utils = ["dep:klvm-utils"]

openssl = ["chik-sha2/openssl", "klvmr/openssl"]

[profile.release]
lto = "thin"

[lib]
bench = false

[workspace.dependencies]
chik_py_streamable_macro = { path = "./crates/chik_py_streamable_macro", version = "0.27.0" }
chik_streamable_macro = { path = "./crates/chik_streamable_macro", version = "0.27.0" }
chik-bls = { path = "./crates/chik-bls", version = "0.27.0" }
chik-client = { path = "./crates/chik-client", version = "0.27.0" }
chik-consensus = { path = "./crates/chik-consensus", version = "0.27.0" }
chik-protocol = { path = "./crates/chik-protocol", version = "0.27.0" }
chik-secp = { path = "./crates/chik-secp", version = "0.27.0" }
chik-ssl = { path = "./crates/chik-ssl", version = "0.27.0" }
chik-traits = { path = "./crates/chik-traits", version = "0.27.0" }
chik-puzzle-types = { path = "./crates/chik-puzzle-types", version = "0.27.0" }
chik-sha2 = { path = "./crates/chik-sha2", version = "0.27.0" }
chik-serde = { path = "./crates/chik-serde", version = "0.27.0" }
klvm-traits = { path = "./crates/klvm-traits", version = "0.27.0" }
klvm-utils = { path = "./crates/klvm-utils", version = "0.27.0" }
klvm-derive = { path = "./crates/klvm-derive", version = "0.27.0" }
chik-fuzz = { path = "./crates/chik-consensus/fuzz", version = "0.27.0" }
chik-bls-fuzz = { path = "./crates/chik-bls/fuzz", version = "0.27.0" }
chik-protocol-fuzz = { path = "./crates/chik-protocol/fuzz", version = "0.27.0" }
chik-puzzle-types-fuzz = { path = "./crates/chik-puzzle-types/fuzz", version = "0.27.0" }
klvm-traits-fuzz = { path = "./crates/klvm-traits/fuzz", version = "0.27.0" }
klvm-utils-fuzz = { path = "./crates/klvm-utils/fuzz", version = "0.27.0" }
blst = { version = "0.3.14", features = ["portable"] }
klvmr = "0.15.0"
syn = "2.0.101"
quote = "1.0.40"
proc-macro2 = "1.0.95"
proc-macro-crate = "1.3.1"
anyhow = "1.0.97"
sha2 = "0.10.9"
hkdf = "0.12.0"
hex = "0.4.3"
thiserror = "1.0.69"
pyo3 = "0.24.1"
arbitrary = "1.4.1"
rand = "0.8.5"
criterion = "0.5.1"
rstest = "0.22.0"
tokio = "1.45.0"
tokio-tungstenite = "0.24.0"
futures-util = "0.3.31"
tungstenite = "0.24.0"
hex-literal = "0.4.1"
num-traits = "0.2.15"
num-bigint = "0.4.5"
text-diff = "0.4.0"
lazy_static = "1.4.0"
rcgen = "0.13.2"
rsa = "0.9.7"
time = "0.3.41"
rusqlite = "0.31.0"
clap = "4.5.38"
zstd = "0.13.3"
blocking-threadpool = "1.0.1"
libfuzzer-sys = "0.4"
wasm-bindgen = "0.2.100"
openssl = "0.10.71"
k256 = "0.13.4"
p256 = "0.13.2"
rand_chacha = "0.3.1"
chik-puzzles = "0.20.1"
serde = "1.0.219"
serde_json = "1.0.140"
bincode = "1.3.3"
indoc = "2.0.6"
linreg = "0.2.0"
gnuplot = "0.0.46"
