[project]
name = "agent-proxy"
version = "0.2.1"
description = ""
authors = [
    {name = "Dutch-voyage",email = "yangyuxuan@zju.edu.cn"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi (==0.100.0)",
    "uvicorn (==0.20.0)",
    "httpx (==0.24.0)",
    "click (==8.0.0)",
    "rich (==13.0.0)"
]


[project.scripts]
http-proxy = "src.agent_proxy.cli:main"
proxy-stats = "src.agent_proxy.cli:stats"
proxy-test = "src.agent_proxy.cli:test"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
    { include = "agent_proxy", from = "src" }
]
